### ISSUE TITLE
Windows build.cmd when new nuget packages added

### ISSUE THREAD

**Issue by manishdube** [lefthandedgoat/canopyStarterKit#7]
Hello Chris,
I am new to packet.dependencies but we are trying to use this canopyStarterKit as our starting point for our automation-CI pipeline. If we are able to add new tests and nuget packages, it would be awesome to trigger build.cmd and run this in a CI model. 
where would we add the new nuget package information so running build.cmd would build the solution and run the tests as you do.
Maybe we are not thinking right but msbuild is not working too well for us.

**Comment by lefthandedgoat** [comment]
To a new project or to canopyStartKiter?

**Comment by manishdube** [comment]
to a project that was built off of canopyStartKit but new tests are being added to it all the time and the intention is to run it in a CI model in jenkins ...

**Comment by lefthandedgoat** [comment]
ok you add nuget references here
https://github.com/lefthandedgoat/canopyStarterKit/blob/master/paket.dependencies

and here
https://github.com/lefthandedgoat/canopyStarterKit/blob/master/canopyStarterKit/paket.references

You can read more about paket here: https://fsprojects.github.io/Paket/

**Comment by manishdube** [comment]
ok. Thanks a lot.
Let me try this.

**Comment by manishdube** [comment]
is this a good way to run a canopy fsproj solution in a CI-jenkins model? 
i.e. run build.cmd as opposed to the msbuild.exe. 
unfortunately msbuild.exe is not working too well on our end.

**Comment by lefthandedgoat** [comment]
yah just run build.cmd from the command line tool in jenkins

**Comment by manishdube** [comment]
thanks again. let us try.

**Comment by manishdube** [comment]
how would i use the Livereport that is generated to be published in github.
currently it shows "http://lefthandedgoat.github.io/canopy/reporttemplatep.html" on the address bar.
Not sure if the solution is writing it somewhere or not?
Sorry ... just a qa guy here.
